"""Add notification preferences

Revision ID: 110dea5d17b1
Revises: 20ea341b7129
Create Date: 2025-12-21 10:48:41.598028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110dea5d17b1'
down_revision: Union[str, Sequence[str], None] = '20ea341b7129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###
