"""Add created_at to users

Revision ID: 20ea341b7129
Revises: 
Create Date: 2025-12-20 23:00:39.444382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ea341b7129'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_executions_id'), 'track_executions', ['id'], unique=False)
    op.create_table('track_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_reviews_id'), 'track_reviews', ['id'], unique=False)
    op.add_column('race_events', sa.Column('continent', sa.String(), nullable=True))
    op.add_column('race_events', sa.Column('country', sa.String(), nullable=True))
    op.add_column('race_events', sa.Column('department', sa.String(), nullable=True))
    op.add_column('race_events', sa.Column('massif', sa.String(), nullable=True))
    op.add_column('race_events', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('users', 'prediction_config',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'profile_picture',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_picture',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'prediction_config',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('race_events', 'city')
    op.drop_column('race_events', 'massif')
    op.drop_column('race_events', 'department')
    op.drop_column('race_events', 'country')
    op.drop_column('race_events', 'continent')
    op.drop_index(op.f('ix_track_reviews_id'), table_name='track_reviews')
    op.drop_table('track_reviews')
    op.drop_index(op.f('ix_track_executions_id'), table_name='track_executions')
    op.drop_table('track_executions')
    # ### end Alembic commands ###
