"""add_nutrition_strategy

Revision ID: 336199aec5c8
Revises: 110dea5d17b1
Create Date: 2025-12-24 15:01:00.978067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336199aec5c8'
down_revision: Union[str, Sequence[str], None] = '110dea5d17b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_strategies', sa.Column('nutrition_strategy', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_strategies', 'nutrition_strategy')
    # ### end Alembic commands ###
