"""Add points_of_interest and update tracks schema

Revision ID: 7e479903212f
Revises: 336199aec5c8
Create Date: 2025-12-24 15:58:41.078308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e479903212f'
down_revision: Union[str, Sequence[str], None] = '336199aec5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('points_of_interest', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'points_of_interest')
    # ### end Alembic commands ###
