"""Add Club model and club_id

Revision ID: cf269540f98a
Revises: 7e479903212f
Create Date: 2025-12-25 21:32:09.503820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf269540f98a'
down_revision: Union[str, Sequence[str], None] = '7e479903212f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Prevent dropping postgis table
    # op.drop_table('spatial_ref_sys')
    
    # op.create_table('clubs',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('name', sa.String(), nullable=True),
    #     sa.Column('description', sa.Text(), nullable=True),
    #     sa.Column('profile_picture', sa.String(), nullable=True),
    #     sa.Column('cover_picture', sa.String(), nullable=True),
    #     sa.Column('website_url', sa.String(), nullable=True),
    #     sa.Column('instagram_url', sa.String(), nullable=True),
    #     sa.Column('strava_club_url', sa.String(), nullable=True),
    #     sa.Column('owner_id', sa.Integer(), nullable=True),
    #     sa.Column('created_at', sa.DateTime(), nullable=True),
    #     sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    # op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=True)
    
    op.add_column('users', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'clubs', ['club_id'], ['id'])
    
    
    # op.add_column('tracks', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'thumbnail_url')
    
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'club_id')
    
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    
    # op.create_table('spatial_ref_sys', ...) # Do not recreate as we didn't drop
    # ### end Alembic commands ###
